packages:
  # all packages in direct subdirs of packages/
  - "backend/**"
  # all packages in subdirs of components/
  - "frontend/**"
  # exclude packages that are inside test directories
  - "!**/test/**"
